#!/bin/bash

declare -i WC
WC=$(pokemon-colorscripts -l | wc | awk '{print $1}' )

declare -i COUNT
COUNT="$WC"

for POKEMON in $(pokemon-colorscripts -l); do
	./jqPoke "$POKEMON" > "./pokeData/$POKEMON"
	((COUNT--))
	PCTLEFT="$((COUNT*100/WC))"
	PCTDONE="$((100-PCTLEFT))"
	printf "\t%s - %s \t%s%%\n" "$COUNT" "$POKEMON" "$PCTDONE"
done

